# -*- coding: utf-8 -*-
"""Copy of innings_total_prediction_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1baANqqNd8lEqcsvaVBKXm2rRf_6OPjwv

# Khel AI — Innings Total Prediction Model

## Sprint 3: From Cricket Data → Machine Learning → `.pkl` → API

This notebook trains a regression model that answers:

> **Given the current state of a T20 innings, what is the predicted final innings total?**

The source data is loaded directly from:

**GitHub repository:** `HimanshuKhale/Cricket_data_8_teams`

### What you will learn

1. Import CSV data directly from GitHub.
2. Define the machine-learning question.
3. Identify features (`X`) and target (`y`).
4. Build leakage-safe innings snapshots.
5. Join data from multiple cricket CSVs.
6. Separate training and test innings correctly.
7. Build a simple cricket baseline.
8. Train multiple regression algorithms.
9. Compare models using MAE, RMSE, and R².
10. Inspect model errors and feature importance.
11. Save the trained pipeline as a `.pkl` file.
12. Reload the `.pkl` and make a new prediction.
13. Understand how the artifact can be served through an API.

---

### Prediction target

`final_innings_total`

The model sees only information that should be available **at the moment of prediction**. It must not see future deliveries or the final score while making the prediction.

## 0. The machine-learning idea

For each live innings snapshot we create one row:

| Input feature | Example |
|---|---:|
| Current score | 92 |
| Wickets lost | 3 |
| Overs completed | 11 |
| Current run rate | 8.36 |
| Pressure index | 0.41 |
| Batter control | 0.76 |
| Bowler control | 0.69 |
| Batting XI strength | 71.4 |
| Bowling XI strength | 67.8 |
| Venue | Emerald Ground, Indore |
| **Target** | **Final score = 174** |

Mathematically:

\[
X = 	ext{current innings state}
\]

\[
y = 	ext{final innings total}
\]

The algorithm learns a function:

\[
\hat{y} = f(X)
\]

where `ŷ` is the predicted final total.

## 1. Install the required libraries

This cell is useful in Google Colab or a fresh Jupyter environment.

If the libraries are already installed, you can skip it.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q "pandas>=2.0" "numpy>=1.24" "scikit-learn>=1.4" "joblib>=1.3" "matplotlib>=3.7"

"""## 2. Import Python libraries"""

from pathlib import Path
import json
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend for Render

import joblib
import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.inspection import permutation_importance
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GroupKFold, GroupShuffleSplit, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

RANDOM_STATE = 42

pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 160)

# ... 3. Import the tournament data directly from GitHub ...

REPO = "HimanshuKhale/Cricket_data_8_teams"
BRANCH = "main"
RAW_BASE = f"https://raw.githubusercontent.com/{REPO}/{BRANCH}"

FILES = {
    "ball_context": "ball_context_features.csv",
    "scoreboard": "innings_scoreboard.csv",
    "matches": "matches.csv",
    "selections": "squad_selections.csv",
    "profiles": "player_profiles.csv",
}

def github_csv(filename: str) -> pd.DataFrame:
    url = f"{RAW_BASE}/{filename}"
    print(f"Loading: {url}")
    return pd.read_csv(url)

ball = github_csv(FILES["ball_context"])
scoreboard = github_csv(FILES["scoreboard"])
matches = github_csv(FILES["matches"])
selections = github_csv(FILES["selections"])
profiles = github_csv(FILES["profiles"])

print("\nLoaded successfully.")

# ... 4. Inspect the imported datasets ...

datasets = {
    "ball_context": ball,
    "scoreboard": scoreboard,
    "matches": matches,
    "selections": selections,
    "profiles": profiles,
}

for name, df in datasets.items():
    print(f"{name:15s} -> rows={len(df):,}, columns={len(df.columns)}")

print("\nball_context_features.csv columns:")
print(pd.DataFrame({"column": ball.columns}).to_string())

print("\n=== ball.head() ===")
print(ball.head().to_string())

print("\n=== scoreboard.head() ===")
print(scoreboard.head().to_string())

# ... 5. Validate that the required columns exist ...

required_ball_columns = {
    "ball_event_id", "match_id", "innings_id", "innings_number",
    "batting_team_id", "bowling_team_id", "phase", "score_before_ball",
    "wickets_before_ball", "legal_balls_before", "target",
    "current_run_rate_before", "required_run_rate_before",
    "pressure_index_before", "batter_control_score_before",
    "bowler_control_score_before", "expected_runs_model",
    "expected_wicket_probability_model",
}

required_scoreboard_columns = {"innings_id", "runs"}
required_match_columns = {"id", "venue"}
required_selection_columns = {"match_id", "team_id", "player_id", "selected"}
required_profile_columns = {
    "player_id", "team_id", "batting_rating", "bowling_rating",
    "pressure_handling", "consistency_rating", "death_batting",
    "line_length_accuracy", "wicket_threat", "death_bowling",
}

checks = [
    ("ball_context_features.csv", required_ball_columns, set(ball.columns)),
    ("innings_scoreboard.csv", required_scoreboard_columns, set(scoreboard.columns)),
    ("matches.csv", required_match_columns, set(matches.columns)),
    ("squad_selections.csv", required_selection_columns, set(selections.columns)),
    ("player_profiles.csv", required_profile_columns, set(profiles.columns)),
]

for filename, required, available in checks:
    missing = required - available
    assert not missing, f"{filename} is missing columns: {sorted(missing)}"

print("Schema validation passed.")

# ... 6. Calculate pre-match strength of each selected XI ...

if selections["selected"].dtype == object:
    selections["selected"] = (
        selections["selected"]
        .astype(str)
        .str.lower()
        .eq("true")
    )
else:
    selections["selected"] = selections["selected"].astype(bool)

selected_xi = (
    selections.loc[selections["selected"]]
    .merge(
        profiles,
        on=["player_id", "team_id"],
        how="left",
        validate="many_to_one",
    )
)

xi_strength = (
    selected_xi
    .groupby(["match_id", "team_id"], as_index=False)
    .agg(
        xi_batting_rating=("batting_rating", "mean"),
        xi_bowling_rating=("bowling_rating", "mean"),
        xi_pressure_handling=("pressure_handling", "mean"),
        xi_consistency=("consistency_rating", "mean"),
        xi_death_batting=("death_batting", "mean"),
        xi_line_length_accuracy=("line_length_accuracy", "mean"),
        xi_wicket_threat=("wicket_threat", "mean"),
        xi_death_bowling=("death_bowling", "mean"),
    )
)

print("Match-team XI strength rows:", len(xi_strength))
print(xi_strength.head().to_string())

# ... 7. Turn ball-by-ball data into innings snapshots ...

snapshots = ball.loc[
    (ball["legal_balls_before"] >= 12)
    & (ball["legal_balls_before"] <= 108)
    & (ball["legal_balls_before"] % 6 == 0)
].copy()

snapshots = (
    snapshots
    .sort_values("ball_event_id")
    .drop_duplicates(["innings_id", "legal_balls_before"])
)

print("Snapshot rows:", len(snapshots))
print("Unique innings:", snapshots["innings_id"].nunique())

# ... 8. Attach the target: final innings total ...

target_table = scoreboard[
    ["innings_id", "runs"]
].rename(columns={"runs": "final_innings_total"})

snapshots = snapshots.merge(
    target_table,
    on="innings_id",
    how="inner",
    validate="many_to_one",
)

assert snapshots["final_innings_total"].notna().all()

print(snapshots[
    [
        "innings_id", "legal_balls_before", "score_before_ball",
        "wickets_before_ball", "final_innings_total",
    ]
].head(10).to_string())

# ... 9. Add venue and XI-strength features ...

snapshots = snapshots.merge(
    matches[["id", "venue"]].rename(columns={"id": "match_id"}),
    on="match_id",
    how="left",
    validate="many_to_one",
)

bat_strength = (
    xi_strength
    .add_prefix("bat_")
    .rename(
        columns={
            "bat_match_id": "match_id",
            "bat_team_id": "batting_team_id",
        }
    )
)

bowl_strength = (
    xi_strength
    .add_prefix("bowl_")
    .rename(
        columns={
            "bowl_match_id": "match_id",
            "bowl_team_id": "bowling_team_id",
        }
    )
)

snapshots = snapshots.merge(
    bat_strength,
    on=["match_id", "batting_team_id"],
    how="left",
    validate="many_to_one",
)

snapshots = snapshots.merge(
    bowl_strength,
    on=["match_id", "bowling_team_id"],
    how="left",
    validate="many_to_one",
)

print("Missing venue values:", snapshots["venue"].isna().sum())
print("Missing batting XI rating:", snapshots["bat_xi_batting_rating"].isna().sum())
print("Missing bowling XI rating:", snapshots["bowl_xi_bowling_rating"].isna().sum())

# ... 10. Create derived match-state features ...

snapshots["balls_remaining"] = 120 - snapshots["legal_balls_before"]
snapshots["overs_completed"] = snapshots["legal_balls_before"] / 6
snapshots["wickets_in_hand"] = 10 - snapshots["wickets_before_ball"]

snapshots["target_filled"] = snapshots["target"].fillna(0)
snapshots["required_run_rate_filled"] = (
    snapshots["required_run_rate_before"].fillna(0)
)

snapshots["runs_required"] = np.where(
    snapshots["innings_number"].eq(2),
    np.maximum(
        snapshots["target_filled"] - snapshots["score_before_ball"],
        0,
    ),
    0,
)

snapshots["projected_score_current_rr"] = (
    snapshots["score_before_ball"]
    + snapshots["current_run_rate_before"]
    * (snapshots["balls_remaining"] / 6)
)

print(snapshots[
    [
        "score_before_ball", "legal_balls_before", "balls_remaining",
        "wickets_in_hand", "current_run_rate_before",
        "projected_score_current_rr", "final_innings_total",
    ]
].head().to_string())

# ... 11. Select model features ...

numeric_features = [
    "innings_number", "score_before_ball", "wickets_before_ball",
    "legal_balls_before", "balls_remaining", "overs_completed",
    "wickets_in_hand", "current_run_rate_before", "target_filled",
    "required_run_rate_filled", "runs_required", "pressure_index_before",
    "batter_control_score_before", "bowler_control_score_before",
    "expected_runs_model", "expected_wicket_probability_model",
    "projected_score_current_rr",
    "bat_xi_batting_rating", "bat_xi_pressure_handling",
    "bat_xi_consistency", "bat_xi_death_batting",
    "bowl_xi_bowling_rating", "bowl_xi_line_length_accuracy",
    "bowl_xi_wicket_threat", "bowl_xi_death_bowling",
]

categorical_features = ["phase", "venue"]
feature_columns = numeric_features + categorical_features

X = snapshots[feature_columns].copy()
y = snapshots["final_innings_total"].astype(float)
groups = snapshots["innings_id"]

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Unique innings:", groups.nunique())

leakage_columns = {
    "final_innings_total", "target_total_runs_this_ball",
    "runs_off_bat_this_ball", "extras_this_ball", "scenario",
}

assert leakage_columns.isdisjoint(feature_columns)
print("Leakage guard passed.")

# ... 12. Look at the target distribution ...

print("\n=== Target Distribution ===")
print(y.describe())

plt.figure(figsize=(8, 5))
plt.hist(y, bins=20)
plt.xlabel("Final innings total")
plt.ylabel("Number of snapshots")
plt.title("Distribution of Final Innings Totals")
plt.savefig("01_target_distribution.png", dpi=100, bbox_inches='tight')
plt.close()
print("Saved: 01_target_distribution.png")

# ... 13. Train/test split by innings ...

splitter = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=RANDOM_STATE,
)

train_idx, test_idx = next(
    splitter.split(X, y, groups=groups)
)

X_train = X.iloc[train_idx].copy()
X_test = X.iloc[test_idx].copy()

y_train = y.iloc[train_idx].copy()
y_test = y.iloc[test_idx].copy()

groups_train = groups.iloc[train_idx].copy()
groups_test = groups.iloc[test_idx].copy()

assert set(groups_train).isdisjoint(set(groups_test))

print("\nTraining rows:", len(X_train))
print("Testing rows:", len(X_test))
print("Training innings:", groups_train.nunique())
print("Testing innings:", groups_test.nunique())

# ... 14. Baseline: current run rate ...

baseline_predictions = X_test[
    "projected_score_current_rr"
].clip(lower=X_test["score_before_ball"])

baseline_mae = mean_absolute_error(
    y_test,
    baseline_predictions,
)
baseline_rmse = np.sqrt(
    mean_squared_error(y_test, baseline_predictions)
)
baseline_r2 = r2_score(
    y_test,
    baseline_predictions,
)

baseline_metrics = pd.DataFrame(
    [
        {
            "model": "Current Run Rate Baseline",
            "MAE": baseline_mae,
            "RMSE": baseline_rmse,
            "R2": baseline_r2,
        }
    ]
)

print("\n=== Baseline Metrics ===")
print(baseline_metrics.round(3).to_string())

# ... 15. Preprocessing Pipeline ...

numeric_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
    ]
)

categorical_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        (
            "onehot",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False,
            ),
        ),
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("numeric", numeric_pipeline, numeric_features),
        (
            "categorical",
            categorical_pipeline,
            categorical_features,
        ),
    ]
)

print("Preprocessing pipeline created.")

# ... 16. Candidate algorithms ...

candidate_models = {
    "Linear Regression": LinearRegression(),

    "Random Forest": RandomForestRegressor(
        n_estimators=300,
        min_samples_leaf=2,
        max_features=0.8,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    ),

    "Gradient Boosting": GradientBoostingRegressor(
        n_estimators=300,
        learning_rate=0.03,
        max_depth=2,
        loss="huber",
        random_state=RANDOM_STATE,
    ),
}

# ... 17. Five-fold grouped cross-validation ...

group_cv = GroupKFold(n_splits=5)

cv_rows = []
trained_models = {}

for model_name, estimator in candidate_models.items():
    pipeline = Pipeline(
        steps=[
            ("preprocess", clone(preprocessor)),
            ("model", estimator),
        ]
    )

    cv_mae = -cross_val_score(
        pipeline,
        X_train,
        y_train,
        groups=groups_train,
        cv=group_cv,
        scoring="neg_mean_absolute_error",
        n_jobs=1,
    )

    pipeline.fit(X_train, y_train)
    trained_models[model_name] = pipeline

    cv_rows.append(
        {
            "model": model_name,
            "CV_MAE_mean": cv_mae.mean(),
            "CV_MAE_std": cv_mae.std(),
        }
    )

cv_results = (
    pd.DataFrame(cv_rows)
    .sort_values("CV_MAE_mean")
    .reset_index(drop=True)
)

print("\n=== Cross-Validation Results ===")
print(cv_results.round(3).to_string())

# ... 18. Select the model using cross-validation ...

best_model_name = cv_results.iloc[0]["model"]
best_model = trained_models[best_model_name]

print("\nSelected model:", best_model_name)

# ... 19. Evaluate the selected model on unseen innings ...

test_predictions = best_model.predict(X_test)

test_mae = mean_absolute_error(y_test, test_predictions)
test_rmse = np.sqrt(
    mean_squared_error(y_test, test_predictions)
)
test_r2 = r2_score(y_test, test_predictions)

comparison = pd.DataFrame(
    [
        {
            "model": "Current Run Rate Baseline",
            "MAE": baseline_mae,
            "RMSE": baseline_rmse,
            "R2": baseline_r2,
        },
        {
            "model": best_model_name,
            "MAE": test_mae,
            "RMSE": test_rmse,
            "R2": test_r2,
        },
    ]
)

print("\n=== Test Set Evaluation ===")
print(comparison.round(3).to_string())

# ... 20. Actual vs predicted ...

plt.figure(figsize=(7, 6))
plt.scatter(y_test, test_predictions, alpha=0.6)

low = min(y_test.min(), test_predictions.min())
high = max(y_test.max(), test_predictions.max())

plt.plot([low, high], [low, high], linestyle="--")
plt.xlabel("Actual final innings total")
plt.ylabel("Predicted final innings total")
plt.title(f"Actual vs Predicted — {best_model_name}")
plt.savefig("02_actual_vs_predicted.png", dpi=100, bbox_inches='tight')
plt.close()
print("Saved: 02_actual_vs_predicted.png")

# ... 21. Residual errors ...

residuals = y_test.to_numpy() - test_predictions

plt.figure(figsize=(8, 5))
plt.hist(residuals, bins=20)
plt.xlabel("Actual - Predicted")
plt.ylabel("Frequency")
plt.title("Prediction Error Distribution")
plt.savefig("03_residuals.png", dpi=100, bbox_inches='tight')
plt.close()
print("Saved: 03_residuals.png")

# ... 22. Error by stage of innings ...

error_analysis = X_test[
    ["overs_completed", "score_before_ball"]
].copy()

error_analysis["actual_total"] = y_test.to_numpy()
error_analysis["predicted_total"] = test_predictions
error_analysis["absolute_error"] = np.abs(
    error_analysis["actual_total"]
    - error_analysis["predicted_total"]
)

error_by_over = (
    error_analysis
    .groupby("overs_completed", as_index=False)
    .agg(
        snapshots=("absolute_error", "size"),
        MAE=("absolute_error", "mean"),
    )
)

print("\n=== Error by Innings Stage ===")
print(error_by_over.round(2).to_string())

plt.figure(figsize=(8, 5))
plt.plot(
    error_by_over["overs_completed"],
    error_by_over["MAE"],
    marker="o",
)
plt.xlabel("Overs completed")
plt.ylabel("Mean absolute error")
plt.title("Model Error by Innings Stage")
plt.savefig("04_error_by_stage.png", dpi=100, bbox_inches='tight')
plt.close()
print("Saved: 04_error_by_stage.png")

# ... 23. Permutation feature importance ...

importance = permutation_importance(
    best_model,
    X_test,
    y_test,
    scoring="neg_mean_absolute_error",
    n_repeats=10,
    random_state=RANDOM_STATE,
    n_jobs=-1,
)

feature_importance = (
    pd.DataFrame(
        {
            "feature": feature_columns,
            "importance": importance.importances_mean,
        }
    )
    .sort_values("importance", ascending=False)
    .head(15)
)

print("\n=== Top 15 Features by Importance ===")
print(feature_importance.round(4).to_string())

plot_df = feature_importance.sort_values("importance")

plt.figure(figsize=(9, 6))
plt.barh(plot_df["feature"], plot_df["importance"])
plt.xlabel("Permutation importance")
plt.title("Top 15 Features")
plt.savefig("05_feature_importance.png", dpi=100, bbox_inches='tight')
plt.close()
print("Saved: 05_feature_importance.png")

# ... 24. Export the model ...

MODEL_FILE = "innings_total_prediction_model.pkl"

artifact = {
    "model": best_model,
    "feature_columns": feature_columns,
    "numeric_features": numeric_features,
    "categorical_features": categorical_features,
    "target": "final_innings_total",
    "model_name": best_model_name,
    "version": "1.0.0",
    "repository": f"https://github.com/{REPO}",
    "snapshot_rule": (
        "one snapshot at over boundaries "
        "from 2 to 18 completed overs"
    ),
    "metrics": {
        "mae": float(test_mae),
        "rmse": float(test_rmse),
        "r2": float(test_r2),
        "baseline_mae": float(baseline_mae),
    },
}

joblib.dump(artifact, MODEL_FILE)

print(f"\nSaved: {MODEL_FILE}")
print("Size:", Path(MODEL_FILE).stat().st_size, "bytes")

# ... 25. Reload the `.pkl` exactly as an API would ...

loaded_artifact = joblib.load(MODEL_FILE)

loaded_model = loaded_artifact["model"]
loaded_features = loaded_artifact["feature_columns"]

print("\nModel:", loaded_artifact["model_name"])
print("Version:", loaded_artifact["version"])
print("Target:", loaded_artifact["target"])
print("Number of features:", len(loaded_features))

# ... 26. Make a prediction from the reloaded model ...

sample = X_test.iloc[[0]].copy()
actual = float(y_test.iloc[0])

raw_prediction = float(
    loaded_model.predict(sample[loaded_features])[0]
)

prediction = max(
    raw_prediction,
    float(sample.iloc[0]["score_before_ball"]),
)

print("\n=== Example Prediction ===")
print("Current score:", sample.iloc[0]["score_before_ball"])
print("Overs completed:", sample.iloc[0]["overs_completed"])
print("Wickets lost:", sample.iloc[0]["wickets_before_ball"])
print("Predicted final total:", round(prediction))
print("Actual final total:", round(actual))

print("\n✓ Script completed successfully!")
